List libraries
PauloniaAQP/mi_libro_vecino_api pull request #4
Opened 2022-03-07 19:12 UTC by oscarnar

Functions to list libraries by state and ubigeo have been created. Please check indices in Firebase.

2022-03-08 01:58 UTC, ChrisChV approved these changes
@oscarnar Buen trabajo, algunos pequeños nits

2022-03-08 01:58 UTC, ChrisChV commented on lib/repositories/library_repository.dart
> +    print(queryRes.docs.last.data());
@oscarnar Eliminar este print

2022-03-08 01:58 UTC, ChrisChV commented on lib/repositories/library_repository.dart
> +    _librariesByState[LibraryState.accepted] = queryRes.docs.last;
@oscarnar Acá antes hay que verificar si `queryRes.docs` tiene elementos o está vacío. Porque si está vacío va a generar error. Recomendo que en el `if` de arriba donde se verifica si el resultado es null, también se verifique si el resultado es vacío

2022-03-08 01:58 UTC, ChrisChV commented on lib/repositories/library_repository.dart
> +    _librariesByUbigeoPagination[type] = queryRes.docs.last;
@oscarnar Lo mismo que lo de arriba

2022-03-08 01:58 UTC, ChrisChV commented on lib/services/auth_service.dart
> +// import 'package:paulonia_error_service/paulonia_error_service.dart';
@oscarnar Esto es por algunos errores al compilar? Errores que salen con `dart:ffi`?

2022-03-08 01:58 UTC, ChrisChV requested changes
.

2022-03-08 03:54 UTC, oscarnar commented on lib/services/auth_service.dart
> +// import 'package:paulonia_error_service/paulonia_error_service.dart';
Siisi al compilar en web da errores de `dart:fii`. Supongo que se debe actualizar ese package para poder correr en web.

2022-03-08 13:57 UTC, ChrisChV commented on lib/services/auth_service.dart
> +// import 'package:paulonia_error_service/paulonia_error_service.dart';
@oscarnar Sii, por ahora para que compile al `pubspec` agrega esta versión del catcher `catcher: 0.6.6` Con eso se soluciona

2022-03-08 14:00 UTC, ChrisChV requested changes
@oscarnar Todo esta bien, descomenta el error service y haz lo de mi comentario para que lo puedas compilar

2022-03-09 00:56 UTC, ChrisChV approved these changes

2022-03-09 00:56 UTC, merged