Search libraries
PauloniaAQP/mi_libro_vecino_api pull request #5
Opened 2022-03-08 19:39 UTC by oscarnar

Search libraries and get libraries by location have been created. `Geopoint` field in firebase has been changed by `GeoFlutterFire` data.

2022-03-09 01:00 UTC, ChrisChV requested changes
@oscarnar LGTM, pequeño nit y resolver conflictos con el anterior PR

2022-03-09 01:00 UTC, ChrisChV commented on lib/services/auth_service.dart
> +// import 'package:paulonia_error_service/paulonia_error_service.dart';
@oscarnar Descomenta esto, para poder hacer merge a este PR

2022-03-21 23:07 UTC, juanleondev approved these changes

2022-03-22 13:20 UTC, ChrisChV approved these changes

2022-04-04 19:21 UTC, merged